name: GridUtils
author: Mooy1
description: More machines and utility items for slimefun
website: https://github.com/Mooy1/GridUtils
main: io.github.mooy1.gridutils.GridUtils
depend: [Slimefun]
softdepend: []
version: ${project.version}
api-version: 1.16

commands:
  gridfoundation:
    description: Do /help gridutils for a list of commands
    usage: /gridutils <subcommand>
    aliases: [grid, gu]

permissions:
  gridutils.admin:
    description: GridUtils admin commands
    default: op