name: GridFoundation
author: Mooy1
description: More machines and utility items for slimefun
website: https://github.com/Mooy1/GridFoundation
main: io.github.mooy1.slimegrid.GridFoundation
depend: [Slimefun, CS-CoreLib]
softdepend: []
version: ${project.version}
api-version: 1.16

commands:
  gridfoundation:
    description: Do /help gridfoundation for a list of commands
    usage: /<command> <subcommand>
    aliases: [gf]

permissions:
  gridfoundation.admin:
    description: GridFoundation admin commands
    default: op