name: SlimeUtils
author: Mooy1
description: More machines and utility items for slimefun
main: io.github.mooy1.slimeutils
website: https://github.com/Mooy1/SlimeUtils
depend: [Slimefun, CS-CoreLib]
softdepend: []
version: ${project.version}
api-version: 1.16
