name: GridExpansion
author: Mooy1
description: More machines and utility items for slimefun
website: https://github.com/Mooy1/GridExpansion
main: io.github.mooy1.gridexpansion.GridExpansion
depend: [Slimefun]
softdepend: []
version: ${project.version}
api-version: 1.16
